version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432